apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dfshell.fullname" . }}
  labels:
    {{- include "dfshell.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dfshell.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dfshell.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dfshell.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.global.datafoldVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sleep", "infinity"]
          envFrom:
            - configMapRef:
                name: {{ include "datafold.configmap" . }}
          env:
            - name: CH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "datafold.secrets" . }}
                  key: DATAFOLD_CLICKHOUSE_PASSWORD
            - name: CH_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "datafold.secrets" . }}
                  key: DATAFOLD_CLICKHOUSE_USER
            - name: CH_SERVER
              value: "{{ include "datafold.clickhouse.server" . }}"
            - name: CH_PORT
              value: "{{ include "datafold.clickhouse.port" . }}"
            - name: CLICKHOUSE_URL
              value: "clickhouse+native://$(CH_USER):$(CH_PASSWORD)@$(CH_SERVER):$(CH_PORT)"
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "datafold.secrets" . }}
                  key: DATAFOLD_POSTGRES_PASSWORD
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "datafold.secrets" . }}
                  key: DATAFOLD_POSTGRES_USER
            - name: PG_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "datafold.secrets" . }}
                  key: DATAFOLD_POSTGRES_DB
            - name: DATAFOLD_DB_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "datafold.secrets" . }}
                  key: DATAFOLD_DB_ENCRYPTION_KEY
            - name: PG_SERVER
              value: "{{ include "datafold.postgres.server" . }}"
            - name: PG_PORT
              value: "{{ include "datafold.postgres.port" . }}"
            - name: DATAFOLD_DATABASE_URL
              value: "postgresql://$(PG_USER):$(PG_PASS)@$(PG_SERVER):$(PG_PORT)/$(PG_DB)"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
