apiVersion: v2
name: datafold
description: Helm chart package to deploy Datafold on kubernetes.
type: application
version: 0.1.7
appVersion: "1.0.0"
icon: https://www.datafold.com/logo.png

maintainers:
  - name: datafold
    email: support@datafold.com
    url: https://datafold.com

dependencies:
  - name: redis
    version: "*.*.*"
    repository: file://charts/redis
    condition: redis.install
  - name: clickhouse
    version: "*.*.*"
    repository: file://charts/clickhouse
    condition: clickhouse.install
  - name: postgres
    version: "*.*.*"
    repository: file://charts/postgres
    condition: postgres.install
  - name: dfshell
    version: "*.*.*"
    repository: file://charts/dfshell
    condition: dfshell.install
  - name: server
    version: "*.*.*"
    repository: file://charts/server
    condition: server.install
