apiVersion: v2
name: datafold
description: Helm chart package to deploy Datafold on kubernetes.
type: application
version: 0.3.1
appVersion: "1.0.0"
icon: https://www.datafold.com/logo.png

maintainers:
  - name: datafold
    email: support@datafold.com
    url: https://datafold.com

dependencies:
  - name: redis
    version: "*.*.*"
    repository: file://charts/redis
    condition: redis.install
  - name: clickhouse
    version: "*.*.*"
    repository: file://charts/clickhouse
    condition: clickhouse.install
  - name: postgres
    version: "*.*.*"
    repository: file://charts/postgres
    condition: postgres.install
  - name: dfshell
    version: "*.*.*"
    repository: file://charts/dfshell
    condition: dfshell.install
  - name: initjob
    version: "*.*.*"
    repository: file://charts/initjob
    condition: initjob.install
  - name: operator
    version: "*.*.*"
    repository: file://charts/operator
    condition: operator.install
  - name: server
    version: "*.*.*"
    repository: file://charts/server
    condition: server.install
  - name: scheduler
    version: "*.*.*"
    repository: file://charts/scheduler
    condition: scheduler.install
  - name: worker
    version: "*.*.*"
    repository: file://charts/worker
    condition: worker.install
  - name: worker-catalog
    version: "*.*.*"
    repository: file://charts/worker_catalog
    condition: worker.install
  - name: worker-interactive
    version: "*.*.*"
    repository: file://charts/worker_interactive
    condition: worker.install
  - name: worker-singletons
    version: "*.*.*"
    repository: file://charts/worker_singletons
    condition: worker.install
  - name: nginx
    version: "*.*.*"
    repository: file://charts/nginx
    condition: nginx.install
  # - name: letsencrypt
  #   version: "*.*.*"
  #   repository: file://charts/letsencrypt
  #   condition: letsencrypt.install
  - name: datadog
    version: "*.*.*"
    repository: file://charts/datadog
    condition: global.datadog.install
