apiVersion: v2
name: datafold
description: Helm chart package to deploy Datafold on kubernetes.
type: application
version: 0.10.17
appVersion: "1.0.0"
icon: https://www.datafold.com/logo.png

maintainers:
  - name: datafold
    email: support@datafold.com
    url: https://datafold.com

dependencies:
  - name: redis
    version: "*.*.*"
    repository: file://charts/redis
    condition: redis.install
  - name: kept
    version: "*.*.*"
    repository: file://charts/kept
    condition: kept.install
  - name: clickhouse
    version: "*.*.*"
    repository: file://charts/clickhouse
    condition: clickhouse.install
  - name: dfshell
    version: "*.*.*"
    repository: file://charts/dfshell
    condition: dfshell.install
  - name: worker-portal
    version: "*.*.*"
    repository: file://charts/worker-portal
    condition: worker-portal.install
  - name: worker-temporal
    version: "*.*.*"
    repository: file://charts/worker-temporal
    condition: worker-temporal.install
  - name: operator
    version: "*.*.*"
    repository: file://charts/operator
    condition: operator.install
  - name: server
    version: "*.*.*"
    repository: file://charts/server
    condition: server.install
  - name: scheduler
    version: "*.*.*"
    repository: file://charts/scheduler
    condition: scheduler.install
  - name: worker
    version: "*.*.*"
    repository: file://charts/worker
    condition: worker.install
    alias: worker
  - name: worker
    version: "*.*.*"
    repository: file://charts/worker
    condition: worker2.install
    alias: worker2
  - name: worker
    version: "*.*.*"
    repository: file://charts/worker
    condition: worker3.install
    alias: worker3
  - name: worker
    version: "0.1.0"
    repository: file://charts/worker
    condition: worker-catalog.install
    alias: worker-catalog
  - name: worker
    version: "0.1.0"
    repository: file://charts/worker
    condition: worker-interactive.install
    alias: worker-interactive
  - name: worker
    version: "0.1.0"
    repository: file://charts/worker
    condition: worker-singletons.install
    alias: worker-singletons
  - name: worker
    version: "0.1.0"
    repository: file://charts/worker
    condition: worker-lineage.install
    alias: worker-lineage
  - name: worker
    version: "0.1.0"
    repository: file://charts/worker
    condition: worker-monitor.install
    alias: worker-monitor
  - name: storage-worker
    version: "0.1.1"
    repository: file://charts/storage-worker
    condition: storage-worker.install
    alias: storage-worker
  - name: storage-worker
    version: "0.1.1"
    repository: file://charts/storage-worker
    condition: storage-worker-large.install
    alias: storage-worker-large
  - name: dma
    version: "0.1.0"
    repository: file://charts/dma
    condition: dma.install
    alias: dma
  - name: dma
    version: "0.1.0"
    repository: file://charts/dma
    condition: dma2.install
    alias: dma2
  - name: dma
    version: "0.1.0"
    repository: file://charts/dma
    condition: dma3.install
    alias: dma3
  - name: nginx
    version: "0.1.0"
    repository: file://charts/nginx
    condition: nginx.install
  - name: datadog
    version: "*.*.*"
    repository: file://charts/datadog
    condition: global.datadog.install
