# The global properties are used to configure multiple charts at once and is a
# keyword that has special scope.
global:
  serverName: "<replace-this>"
  common:
    labels: {}
    annotations: {}
  deployment: ""
  storageClass: ""
  awsTargetGroupArn: ""
  vpcCidr: ""
  cloudProvider: ""
  authMethod: "password"
  statusCheckToken: "magic_token"
  datafoldRepository: "us-docker.pkg.dev/datadiff-mm/datafold"
  shellRepository: "us-docker.pkg.dev/datadiff-mm/datafold"
  clickhouse:
    port: 9000
    storageOnPV: "true"
    database: "clickhouse"
  postgres:
    port: 5432
    storageOnPV: "true"
  redis:
    port: 6379
    storageOnPV: "true"
  server:
    # Application will fail if the port is not set to 5000
    port: 5000
  nginx:
    port: 80
    gcpNegName: ""
  datadog:
    install: false
    env: "prod"
    host: ""
    logs:
      port: 10518
    metrics:
      port: 8125
  operator:
    allowRollback: "false"
    releaseChannel: "change-this"
    backupCronSchedule: "0 1 * * *"
    maintenanceWindow: ""

# ------------------------------------------------------------------------------
# These are properties only used by the charts and templates on this level.
redis:
  install: true

clickhouse:
  install: true

postgres:
  install: true

dfshell:
  install: true

initjob:
  install: true

operator:
  install: true

server:
  install: true

scheduler:
  install: true

worker:
  install: true

nginx:
  install: true

config:
  webWorkers: "30"
  workerCount: "15"
  githubServer: ""
  gitlabServer: ""
  maxTasksPerWorker: "200"
  maxMemPerWorker: "300000"
  ratelimitEnabled: "true"
  loggingEnabled: "true"
  singleTenantDeploy: "true"
  mailPort: "587"
  mailUseTls: "true"
  mailUseSsl: "false"
  enableSsrfProtection: "true"
  logLevel: "INFO"
  enforceHttps: "false"
  googleOauthRequestBQ: "true"
  ddTraceEnabled: "false"
  ddDogStatsDisable: "false"
  floatFormat: "0,0.00[0000000]"
  dateFormat: "YYYY-MM-DD"
  timeFormat: "HH:mm:ss"
  alertsWithMultiDimAndMultiField: ""
  enableGraphInvariantsChecks: "false"
  lineageTestingDb: ""
  contentSecurityPolicy: "default-src 'self'; connect-src 'self' raw.githubusercontent.com api.perfalytics.com perfalytics.com api.avo.app track.customer.io www.google-analytics.com browser-http-intake.logs.datadoghq.com browser-intake-datadoghq.com *.browser-intake-datadoghq.com forms.hubspot.com *.ingest.sentry.io api.segment.io *.intercom.io *.intercomcdn.com wss://*.intercom.io ; style-src 'self' 'unsafe-inline' fonts.googleapis.com; script-src 'self' 'unsafe-eval' perfalytics.com assets.customer.io js.intercomcdn.com *.hs-scripts.com js.hs-scripts.com js.hs-banner.com js.hscollectedforms.net cdn.segment.com widget.intercom.io js.intercomcdn.com www.google-analytics.com js.hs-analytics.net https://www.google-analytics.com; font-src 'self' data: fonts.gstatic.com js.intercomcdn.com; img-src 'self' http: https: data:; object-src 'none'; frame-ancestors 'none'; worker-src 'self' blob:; frame-src 'self calendly.com;"
  forceFeatures: "datadiff,profiling,alerts,catalog,ci,lineage,experimental_search,jobs,saml,tsch:w,tsch:r,saml_groups_mapping,hightouch,xdiff"
  enabledFeatures: "datadiff,profiling,alerts,catalog,ci,lineage,experimental_search,jobs,saml,restricted,tsch:w,tsch:r,saml_groups_mapping,hightouch,clickhouse_statements:shadow_write,clickhouse_graph:shadow_write,clickhouse_graph:enabled,xdiff,ch_lineage_enqueue,ch_lineage_process,ch_schema"
  enabledDestinations: "datafold.destinations.email,datafold.destinations.slack,datafold.destinations.webhook,datafold.destinations.pagerduty"
  customerAdaptation: ""

secrets:
  installMePassword: "-"
  imagePull: ""
  googleClientId: ""
  googleclientSecret: ""
  intercomId: ""
  database:
    encryptionKey: "-"
  mail:
    server: "-"
    username: "-"
    password: "-"
    defaultSender: "-"
  clickhouse:
    user: "-"
    password: "-"
  postgres:
    user: "-"
    password: "-"
    database: "-"
  redis:
    password: "-"
  datadog:
    apiKey: ""
    appKey: ""
    clientToken: "client-token"
    applicationId: "application-id"
  freshpaint:
    backendToken: ""
    frontendToken: ""
    url: "https://api.perfalytics.com/track"
    avoToken: ""
