# The global properties are used to configure multiple charts at once and is a
# keyword that has special scope.
global:
  serverName: chiel.dev.datafold.io
  common:
    labels: {}
    annotations: {}
  storageClass: ""
  cloudProvider: "aws"
  authMethod: "password"
  statusCheckToken: "magic_token"
  datafoldVersion: ""
  datafoldRepository: "us-docker.pkg.dev/datadiff-mm/datafold/server"
  shellRepository: "us-docker.pkg.dev/datadiff-mm/datafold/server"
  ingressClassName: traefik
  clickhouse:
    port: 9000
    storageOnPV: "true"
  postgres:
    port: 5432
    storageOnPV: "true"
  redis:
    port: 6379
    storageOnPV: "true"
  server:
    # Application will fail if the port is not set to 5000
    port: 5000
  nginx:
    port: 80

# ------------------------------------------------------------------------------
# These are properties only used by the charts and templates on this level.
redis:
  install: true

clickhouse:
  install: true

postgres:
  install: true

dfshell:
  install: true

server:
  install: true

scheduler:
  install: true

worker:
  install: true

config:
  webWorkers: "30"
  workerCount: "90"
  githubServer: "https://github.com"
  maxTasksPerWorker: "200"
  maxMemPerWorker: "300000"
  ratelimitEnabled: "true"
  loggingEnabled: "true"
  singleTenantDeploy: "true"
  mailPort: "25"
  mailUseTls: "false"
  mailUseSsl: "false"
  enableSsrfProtection: "true"
  logLevel: "INFO"
  enforceHttps: "false"
  googleOauthRequestBQ: "true"
  ddTraceEnabled: "false"
  ddDogStatsDisable: "true"
  ddEnv: "prod"
  floatFormat: "0,0.00[0000000]"
  dateFormat: "YYYY-MM-DD"
  timeFormat: "HH:mm:ss"
  alertsWithMultiDimAndMultiField: ""
  enableGraphInvariantsChecks: "true"
  lineageTestingDb: ""
  freshpaintBackend: ""
  freshpaintFrontend: ""
  freshpaintUrl: "https://api.perfalytics.com2/track"
  avoToken: ""

secrets:
  installMePassword: "-"
  database:
    encryptionKey: "-"
  mail:
    server: "-"
    username: "-"
    password: "-"
    defaultSender: "-"
  clickhouse:
    user: "-"
    password: "-"
  postgres:
    user: "-"
    password: "-"
    database: "-"
  redis:
    password: "-"
