# The global properties are used to configure multiple charts at once and is a
# keyword that has special scope.
global:
  serverName: "<replace-this>"
  customSecrets: []
  common:
    labels: {}
    annotations: {}
  deployment: ""
  storageClass: ""
  awsTargetGroupArn: ""
  vpcCidr: ""
  cloudProvider: ""
  authMethod: "password"
  statusCheckToken: "magic_token"
  datafoldRepository: "us-docker.pkg.dev/datadiff-mm/datafold"
  shellRepository: "us-docker.pkg.dev/datadiff-mm/datafold"
  optional:
    intercom: "false"
    pylon: "false"
    googleAuth: "false"
  clickhouse:
    port: 9000
    storageOnPV: "true"
    database: "clickhouse"
  postgres:
    port: 5432
    storageOnPV: "true"
    datadogpw: ""
  redis:
    port: 6379
    storageOnPV: "true"
  server:
    # Application will fail if the port is not set to 5000
    port: 5000
  nginx:
    port: 80
    gcpNegName: ""
  datadog:
    install: false
    env: "prod"
    host: ""
    logs:
      port: 10518
    metrics:
      port: 8125
    apm:
      port: 8126
  operator:
    allowRollback: "false"
    releaseChannel: "change-this"
    backupCronSchedule: "0 1 * * *"
    maintenanceWindow: ""

# ------------------------------------------------------------------------------
# These are properties only used by the charts and templates on this level.
redis:
  install: true

clickhouse:
  install: true

postgres:
  install: true

dfshell:
  install: true

initjob:
  install: false

operator:
  install: true

server:
  install: true

scheduler:
  install: true

nginx:
  install: true

config:
  webWorkers: "4"
  workerCount: "15"
  githubServer: ""
  gitlabServer: ""
  maxTasksPerWorker: "200"
  maxMemPerWorker: "300000"
  ratelimitEnabled: "true"
  rateLimitHighLoadPerMinute: "120"
  loggingEnabled: "true"
  singleTenantDeploy: "true"
  mailPort: "587"
  mailUseTls: "true"
  mailUseSsl: "false"
  enableSsrfProtection: "true"
  logLevel: "INFO"
  enforceHttps: "true"
  googleOauthRequestBQ: "false"
  ddTraceEnabled: "false"
  ddApmAddress: ""
  ddDogStatsDisable: "false"
  floatFormat: "0,0.00[0000000]"
  dateFormat: "YYYY-MM-DD"
  timeFormat: "HH:mm:ss"
  alertsWithMultiDimAndMultiField: ""
  enableGraphInvariantsChecks: "false"
  lineageTestingDb: ""
  contentSecurityPolicy: "default-src 'self'; connect-src 'self' *.usepylon.com *.posthog.com *.pusher.com raw.githubusercontent.com api.perfalytics.com perfalytics.com api.avo.app track.customer.io www.google-analytics.com browser-http-intake.logs.datadoghq.com browser-intake-datadoghq.com *.browser-intake-datadoghq.com forms.hubspot.com wss://*.hotjar.com *.hotjar.io *.analytics.google.com *.g.doubleclick.net api.amplitude.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com *.usepylon.com *.posthog.com *.pusher.com; script-src 'self' 'unsafe-eval' 'unsafe-inline' *.usepylon.com *.posthog.com *.pusher.com perfalytics.com assets.customer.io *.hs-scripts.com js.hs-scripts.com js.hs-banner.com js.hscollectedforms.net www.google-analytics.com js.hs-analytics.net https://www.google-analytics.com *.googletagmanager.com *.hotjar.com cdn.jsdelivr.net cdn.amplitude.com; font-src 'self' data: fonts.gstatic.com *.usepylon.com *.posthog.com *.pusher.com; img-src 'self' http: https: data:; object-src 'none'; frame-ancestors 'none'; worker-src 'self' blob:; frame-src 'self' calendly.com;"
  customerAdaptation: ""
  customVars: []

secrets:
  installMePassword: "-"
  googleClientId: ""
  googleclientSecret: ""
  intercomId: ""
  pylonId: ""
  database:
    encryptionKey: "-"
  mail:
    server: "-"
    username: "-"
    password: "-"
    defaultSender: "-"
  clickhouse:
    user: "-"
    password: "-"
  postgres:
    user: "-"
    password: "-"
    database: "-"
  redis:
    password: "-"
  datadog:
    apiKey: ""
    appKey: ""
    clientToken: "client-token"
    applicationId: "application-id"
  freshpaint:
    backendToken: ""
    frontendToken: ""
    url: "https://api.perfalytics.com/track"
    avoToken: ""

worker:
  install: true
  replicaCount: 1
  terminationGracePeriodSeconds: "1800"
  worker:
    queues: "celery,api,ci,interactive,freshpaint,alerts"
    tasks: 200
    memory: 850000
    count: 15
  resources:
    limits:
      memory: 12000Mi
    requests:
      cpu: 1000m
      memory: 12000Mi

worker2:
  install: false
  replicaCount: 1
  terminationGracePeriodSeconds: "1800"
  worker:
    queues: "celery,api,ci,interactive,freshpaint,alerts"
    tasks: 200
    memory: 850000
    count: 15
  resources:
    limits:
      memory: 12000Mi
    requests:
      cpu: 1000m
      memory: 12000Mi

worker3:
  install: false
  replicaCount: 1
  terminationGracePeriodSeconds: "1800"
  worker:
    queues: "celery,api,ci,interactive,freshpaint,alerts"
    tasks: 200
    memory: 850000
    count: 15
  resources:
    limits:
      memory: 12000Mi
    requests:
      cpu: 1000m
      memory: 12000Mi

worker-catalog:
  install: true
  replicaCount: 1
  terminationGracePeriodSeconds: "30"
  worker:
    queues: "lineage,catalog"
    tasks: 200
    memory: 850000
    count: 5
  resources:
    limits:
      memory: 13000Mi
    requests:
      cpu: 1000m
      memory: 13000Mi

worker-interactive:
  install: true
  replicaCount: 1
  terminationGracePeriodSeconds: "300"
  worker:
    queues: "interactive"
    tasks: 200
    memory: 850000
    count: 5
  resources:
    limits:
      memory: 4000Mi
    requests:
      cpu: 100m
      memory: 4000Mi

worker-singletons:
  install: true
  replicaCount: 1
  terminationGracePeriodSeconds: "30"
  worker:
    queues: "singletons"
    tasks: 200
    memory: 850000
    count: 4
  resources:
    limits:
      memory: 3000Mi
    requests:
      cpu: 100m
      memory: 3000Mi

worker-lineage:
  install: false

worker-monitor:
  install: false
