# The global properties are used to configure multiple charts at once
# and is a keyword that has special scope.
global:
  # This should be the fqdn of where your users will be accessing the instance.
  host: "http://localhost:8080"
  common:
    labels: {}
    annotations: {}
  storageClass: ""
  authMethod: "password"
  datafoldVersion: ""
  clickhouse:
    port: 9000
  postgres:
    port: 5432
  redis:
    port: 6379

redis:
  install: true

clickhouse:
  install: true

postgres:
  install: true

dfshell:
  install: true

config:
  webWorkers: "30"
  workerCount: "90"
  githubServer: "https://github.com"
  maxTasksPerWorker: "200"
  maxMemPerWorker: "300000"
  ratelimitEnabled: "true"
  loggingEnabled: "true"
  singleTenantDeploy: "true"
  mailPort: "25"
  mailUseTls: "false"
  mailUseSsl: "false"
  enableSsrfProtection: "true"

secrets:
  installMePassword: "-"
  database:
    encryptionKey: "-"
  mail:
    server: "-"
    username: "-"
    password: "-"
    defaultSender: "-"
  clickhouse:
    user: "-"
    password: "-"
  postgres:
    user: "-"
    password: "-"
    database: "-"
