# The global properties are used to configure multiple charts at once and is a
# keyword that has special scope.
global:
  serverName: "<replace-this>"
  common:
    labels: {}
    annotations: {}
  deployment: ""
  storageClass: ""
  awsTargetGroupArn: ""
  vpcCidr: ""
  cloudProvider: ""
  authMethod: "password"
  statusCheckToken: "magic_token"
  datafoldRepository: "us-docker.pkg.dev/datadiff-mm/datafold"
  shellRepository: "us-docker.pkg.dev/datadiff-mm/datafold"
  clickhouse:
    port: 9000
    storageOnPV: "true"
    database: "clickhouse"
  postgres:
    port: 5432
    storageOnPV: "true"
  redis:
    port: 6379
    storageOnPV: "true"
  server:
    # Application will fail if the port is not set to 5000
    port: 5000
  nginx:
    port: 80
    gcpNegName: ""
  datadog:
    install: false
    env: "prod"
    host: ""
    logs:
      port: 10518
    metrics:
      port: 8125
  operator:
    allowRollback: "false"
    releaseChannel: "change-this"
    backupCronSchedule: "0 1 * * *"
    maintenanceWindow: ""

# ------------------------------------------------------------------------------
# These are properties only used by the charts and templates on this level.
redis:
  install: true

clickhouse:
  install: true

postgres:
  install: true

dfshell:
  install: true

initjob:
  install: true

operator:
  install: true

server:
  install: true

scheduler:
  install: true

worker:
  install: true

nginx:
  install: true

config:
  webWorkers: "30"
  workerCount: "15"
  githubServer: "https://github.com"
  maxTasksPerWorker: "200"
  maxMemPerWorker: "300000"
  ratelimitEnabled: "true"
  loggingEnabled: "true"
  singleTenantDeploy: "true"
  mailPort: "25"
  mailUseTls: "false"
  mailUseSsl: "false"
  enableSsrfProtection: "true"
  logLevel: "INFO"
  enforceHttps: "false"
  googleOauthRequestBQ: "true"
  ddTraceEnabled: "false"
  ddDogStatsDisable: "false"
  floatFormat: "0,0.00[0000000]"
  dateFormat: "YYYY-MM-DD"
  timeFormat: "HH:mm:ss"
  alertsWithMultiDimAndMultiField: ""
  enableGraphInvariantsChecks: "true"
  lineageTestingDb: ""

secrets:
  installMePassword: "-"
  imagePull: ""
  database:
    encryptionKey: "-"
  mail:
    server: "-"
    username: "-"
    password: "-"
    defaultSender: "-"
  clickhouse:
    user: "-"
    password: "-"
  postgres:
    user: "-"
    password: "-"
    database: "-"
  redis:
    password: "-"
  datadog:
    apiKey: ""
    appKey: ""
    clientToken: "client-token"
    applicationId: "application-id"
  freshpaint:
    backendToken: ""
    frontendToken: ""
    url: "https://api.perfalytics.com/track"
    avoToken: ""
