# The global properties are used to configure multiple charts at once
# and is a keyword that has special scope.
global:
  # This should be the fqdn of where your users will be accessing the instance.
  host: "http://localhost:8080"
  common:
    labels: {}
    annotations: {}
  storageClass: ""
  cloudProvider: "aws"
  authMethod: "password"
  datafoldVersion: ""
  clickhouse:
    port: 9000
    storageOnPV: "true"
  postgres:
    port: 5432
    storageOnPV: "true"
  redis:
    port: 6379
    storageOnPV: "true"
  server:
    port: 5000
    hostName: k8s.dev.local

redis:
  install: true

clickhouse:
  install: true

postgres:
  install: true

dfshell:
  install: true

server:
  install: true

config:
  webWorkers: "30"
  workerCount: "90"
  githubServer: "https://github.com"
  maxTasksPerWorker: "200"
  maxMemPerWorker: "300000"
  ratelimitEnabled: "true"
  loggingEnabled: "true"
  singleTenantDeploy: "true"
  mailPort: "25"
  mailUseTls: "false"
  mailUseSsl: "false"
  enableSsrfProtection: "true"
  logLevel: "INFO"
  enforceHttps: "false"
  googleOauthRequestBQ: "true"
  ddTraceEnabled: "false"
  ddDogStatsDisable: "true"
  ddEnv: "prod"
  floatFormat: "0,0.00[0000000]"
  dateFormat: "YYYY-MM-DD"
  timeFormat: "HH:mm:ss"
  alertsWithMultiDimAndMultiField: ""
  enableGraphInvariantsChecks: "true"
  lineageTestingDb: ""
  freshpaintBackend: ""
  freshpaintfrontend: ""
  freshpaintUrl: "https://api.perfalytics.com2/track"
  avoToken: ""

secrets:
  installMePassword: "-"
  database:
    encryptionKey: "-"
  mail:
    server: "-"
    username: "-"
    password: "-"
    defaultSender: "-"
  clickhouse:
    user: "-"
    password: "-"
  postgres:
    user: "-"
    password: "-"
    database: "-"
  redis:
    password: "-"
