# The global properties are used to configure multiple charts at once
# and is a keyword that has special scope.
global:
  # This should be the fqdn of where your users will be accessing the instance.
  host: "http://localhost:8080"
  common:
    labels: {}
    annotations: {}
  storageClass: ""

redis:
  install: true

clickhouse:
  install: true

config:
  web_workers: "30"
  worker_count: "90"
  github_server: "https://github.com"
  max_tasks_per_worker: "200"
  max_mem_per_worker: "300000"
  ratelimit_enabled: "true"
  logging_enabled: "true"
  single_tenant_deploy: "true"
  mail_port: "25"
  mail_use_tls: "false"
  mail_use_ssl: "false"
  enable_ssrf_protection: "true"

secrets:
  install_me_password: "-"
  database:
    encryption_key: "-"
  mail:
    server: "-"
    username: "-"
    password: "-"
    default_sender: "-"
  clickhouse:
    user: "default"
    password: "default"
