apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worker.fullname" . }}
  labels:
    {{- include "worker.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.replicaCount }}
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "worker.datafold.annotations" . | nindent 8 }}
        {{- include "worker.datadog.annotations" . | nindent 8 }}
      labels:
        {{- include "worker.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.datafoldRepository }}/{{ .Values.global.datafoldImage }}:{{ .Values.global.datafoldVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["{{ .Values.command }}"]
          envFrom:
            - configMapRef:
                name: {{ include "datafold.configmap" . }}
          env:
            {{ include "worker.env" . | nindent 12 }}
            {{ include "datafold.env" . | nindent 12 }}
            - name: DATAFOLD_CELERY_TASKS_ACK_LATE
              value: "{{ .Values.worker.tasks_ack_late }}"
            - name: DATAFOLD_FRESHPAINT_BACKEND_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "datafold.secrets" . }}
                  key: DATAFOLD_FRESHPAINT_BACKEND_TOKEN
            - name: DATAFOLD_FRESHPAINT_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "datafold.secrets" . }}
                  key: DATAFOLD_FRESHPAINT_URL
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /app/bin/docker-entrypoint celery_healthcheck
            initialDelaySeconds: 60
            periodSeconds: 180
            failureThreshold: 2
            successThreshold: 1
            timeoutSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- include "worker.volume.mounts" . | nindent 12 }}
            {{- with .Values.volumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- include "worker.volumes" . | nindent 8 }}
        {{- with .Values.volumes }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
