replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
terminationGracePeriodSeconds: "900"

storage:
  size: 100Gi
  storageClass: ""
  volumeId: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsUser: 70
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 5432

resources:
  limits:
    memory: 3000Mi
  requests:
    cpu: 1000m
    memory: 3000Mi

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
