replicaCount: 1

image:
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: datafold-docker-secret
nameOverride: ""
fullnameOverride: ""

command: scheduler

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false

resources:
  limits:
    memory: 2000Mi
  requests:
    cpu: 100m
    memory: 2000Mi

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
