replicaCount: 1

image:
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: datafold-docker-secret
nameOverride: ""
fullnameOverride: ""
terminationGracePeriodSeconds: "5"

command: scheduler

serviceAccount:
  create: true
  automount: true
  annotations: {}
  roleArn: ""
  name: "datafold-scheduler"

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false

resources:
  limits:
    memory: 2000Mi
  requests:
    cpu: 100m
    memory: 2000Mi

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
