apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.awsBedrockIrsa.serviceAccount.name }}
  labels:
    {{- include "awsBedrockIrsa.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.serviceAccount.annotations }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
    {{- end }}
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}