{{- $files := .Files }}
{{- $path := "secrets-decrypted/secrets.yaml"}}
{{- $secretData := $files.Get $path | fromYaml }}
apiVersion: v1
kind: Secret
metadata:
  name: datafold-secrets
  namespace: medium
type: Opaque
data:
{{- range $name, $secret := ($secretData) }}
  {{ $name }}: {{ $secret | b64enc }}
{{- end }}
---
