replicaCount: 0
image:
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: datafold-docker-secret
nameOverride: ""
fullnameOverride: ""
terminationGracePeriodSeconds: "5"

command:
  - "./manage.py"
  - "temporal"
  - "start-worker"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  roleArn: ""
  name: "datafold-worker-temporal"

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: False

resources:
  limits:
    memory: 1000Mi
  requests:
    cpu: 100m
    memory: 1000Mi

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

initContainers: []
