{{- if not .Values.global.hostPath -}}
# Extend with additional checks, we only want to create one volume here
{{ fail "This version must use global.hostPath setting" }}
{{- end -}}

{{- if .Values.global.hostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.storage.name }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  {{- include "datafold.storageClass" . | nindent 2 }}
  accessModes:
    - ReadWriteOnce
  # capacity.storage is required, but in a PV it is only a label
  capacity:
    storage: {{ .Values.storage.size }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.global.hostPath }}/deploy/data/clickhouse
    type: Directory
{{- end }}
