{{- if .Values.storage.volumeId }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "clickhouse.data.pv.name" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  capacity:
    storage: {{ .Values.storage.dataSize }}
  {{- include "datafold.storageClass" . | nindent 2 }}
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.storage.volumeId }}
  claimRef:
    name: {{ include "clickhouse.data.pvc.name" . }}
{{- end }}
