apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.secrets" . }}
type: Opaque
data:
  S3_ACCESS_KEY: {{ .Values.secrets.access_key | b64enc }}
  S3_SECRET_KEY: {{ .Values.secrets.secret_key | b64enc }}
  GCS_CREDENTIALS_JSON: {{ .Values.secrets.clickhouse_backup_sa }}
  AZBLOB_ACCOUNT_KEY: {{ .Values.secrets.azblob_account_key | b64enc }}
