apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.secrets" . }}
type: Opaque
data:
  GCS_CREDENTIALS_JSON: {{ .Values.secrets.clickhouse_backup_sa }}
  AZBLOB_ACCOUNT_KEY: {{ .Values.secrets.azblob_account_key | b64enc }}
