apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "clickhouse.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "clickhouse.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "clickhouse.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MAX_SERVER_MEMORY_USAGE_TO_RAM_RATIO
              value: "0.2"
            - name: USER_PASSWORD
              value: default
            - name: UNCOMPRESSED_CACHE_SIZE
              value: "536870912"
            - name: MAX_CONCURRENT_QUERIES
              value: "300"
            - name: MARK_CACHE_SIZE
              value: "1073741824"
          ports:
            - name: clickhouse
              containerPort: 9000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "clickhouse.pvc.name" . }}
              mountPath: /data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "clickhouse.pvc.name" . }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{ include "datafold.storageClass" . | nindent 8 }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
{{- if .Values.global.hostPath }}
        volumeName: {{ include "clickhouse.pv.name" . }}
{{- end }}
