{{- if .Values.storage.dataVolumeId }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "redis.data.pv.name" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  capacity:
    storage: {{ .Values.storage.dataSize }}
  {{- include "datafold.storageClass" . | nindent 2 }}
  persistentVolumeReclaimPolicy: Retain
{{- if (eq .Values.global.cloudProvider "aws") }}
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: {{ .Values.storage.dataVolumeId }}
    fsType: "ext4"
{{- end }}
{{- if (eq .Values.global.cloudProvider "gcp") }}
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: {{ .Values.storage.dataVolumeId }}
    fsType: "ext4"
{{- end }}
{{- if (eq .Values.global.cloudProvider "azure") }}
  fail "PV for azure not implemented yet." }}
{{- end }}
{{- end }}
