replicaCount: 2

image:
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: datafold-docker-secret
nameOverride: ""
fullnameOverride: ""
terminationGracePeriodSeconds: "120"

command: "server"

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false

service:
  type: ClusterIP

ingress:
  enabled: true
  className: ""
  annotations: {}
  path: /
  pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    memory: 6Gi
  requests:
    cpu: 500m
    memory: 6Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - server
            - key: app.kubernetes.io/instance
              operator: In
              values:
                - datafold
        topologyKey: "kubernetes.io/hostname"
