replicaCount: 1

image:
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: datafold-docker-secret
nameOverride: ""
fullnameOverride: ""
terminationGracePeriodSeconds: "5"

command: "server"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP

ingress:
  enabled: true
  className: ""
  annotations: {}
  path: /
  pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    memory: 3000Mi
  requests:
    cpu: 500m
    memory: 3000Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
