apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "initjob.fullname" . }}
  labels:
    {{- include "initjob.labels" . | nindent 4 }}
spec:
  template:
    spec:
      ttlSecondsAfterFinished: 100
      containers:
        - name: init-postgres
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.shellRepository }}/{{ .Values.global.datafoldImage }}:{{ .Values.global.datafoldVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bash
            - -c
            - ./manage.py database wait-for-connection && ./manage.py database create-or-upgrade && ./manage.py installation set-new-deployment-params
          envFrom:
            - configMapRef:
                name: {{ include "datafold.configmap" . }}
          env:
            {{ include "datafold.env" . | nindent 12 }}
        - name: init-clickhouse
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.shellRepository }}/{{ .Values.global.datafoldImage }}:{{ .Values.global.datafoldVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bash
            - -c
            - ./manage.py clickhouse wait-for-connection && ./manage.py clickhouse create-or-upgrade
          envFrom:
            - configMapRef:
                name: {{ include "datafold.configmap" . }}
          env:
            {{ include "datafold.env" . | nindent 12 }}
      restartPolicy: OnFailure
  backoffLimit: 4
