apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dma.fullname" . }}-data
  labels:
    {{- include "dma.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}