apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: {{ include "datadog.fullname" . }}
  labels:
    {{- include "datadog.labels" . | nindent 4 }}
spec:
  global:
    credentials:
      apiSecret:
        secretName: {{ include "datafold.secrets" . }}
        keyName: DATAFOLD_DD_API_KEY
      appSecret:
        secretName: {{ include "datafold.secrets" . }}
        keyName: DATAFOLD_DD_APP_KEY
    {{- include "datadog.global.config" . | nindent 4 }}
    tags:
      - "env:{{ .Values.global.datadog.env }}"
      - '{{ include "datadog.deployment.tag" . }}'
    logLevel: "{{ .Values.configuration.logLevel }}"
  features:
    {{- include "datadog.features" . | nindent 4 }}
    logCollection:
      enabled: {{ .Values.configuration.logCollection.enabled }}
      containerCollectAll: {{ .Values.configuration.logCollection.containerCollectAll }}
    liveProcessCollection:
      enabled: {{ .Values.configuration.liveProcessCollection }}
    liveContainerCollection:
      enabled: {{ .Values.configuration.liveContainerCollection }}
    processDiscovery:
      enabled: {{ .Values.configuration.processDiscovery }}
    oomKill:
      enabled: {{ .Values.configuration.oomKill }}
    apm:
      enabled: {{ .Values.configuration.apm }}
      hostPortConfig:
        enabled: {{ .Values.configuration.apm }}
    dogstatsd:
      enabled: {{ .Values.configuration.dogstatsd.enabled }}
      tagCardinality: {{ .Values.configuration.dogstatsd.tagCardinality }}
      hostPortConfig:
        enabled: {{ .Values.configuration.dogstatsd.hostPortConfig }}
        hostPort: 8125
  override:
    {{- include "datadog.clusteragent.overrides" . | nindent 4 }}
    nodeAgent:
      env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "datafold.secrets" . }}
              key: DATAFOLD_REDIS_PASSWORD
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "datafold.secrets" . }}
              key: DATAFOLD_CLICKHOUSE_PASSWORD
        - name: CLICKHOUSE_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "datafold.secrets" . }}
              key: DATAFOLD_CLICKHOUSE_USER
        - name: DD_CONTAINER_EXCLUDE
          value: "image:gcr.io/datadoghq.*"
      extraConfd:
         configDataMap:
           python.yaml: |-
             logs:
               - type: tcp
                 port: {{ include "datafold.datadog.logs.port" . }}
                 service: datafold
                 source: app
                 sourcecategory: sourcecode
