apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "datadog.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: [{{ include "datafold.secrets" . }}]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "datadog.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "datadog.fullname.agent" . }}
    apiGroup: ""
    namespace: {{ .Values.global.deployment }}
roleRef:
  kind: Role
  name: {{ include "datadog.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "datadog.fullname" . }}-temporal-secrets
  namespace: temporal
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["datadog.temporal-database.credentials.postgresql.acid.zalan.do"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "datadog.fullname" . }}-temporal-secrets
  namespace: temporal
subjects:
  - kind: ServiceAccount
    name: {{ include "datadog.fullname.agent" . }}
    apiGroup: ""
    namespace: {{ .Values.global.deployment }}
roleRef:
  kind: Role
  name: {{ include "datadog.fullname" . }}-temporal-secrets
  apiGroup: rbac.authorization.k8s.io
