apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datafold.fullname" . }}-config
data:
  PYTHONUNBUFFERED: "0"
  DATAFOLD_WEB_WORKERS: "{{ .Values.config.web_workers }}"
  GITHUB_SERVER: "{{ .Values.config.github_server }}"
  DEV_NAME: "{{ .Release.Name }}"
  INSTALLATION_NAME: "{{ .Release.Name }}"
  WORKERS_COUNT: "{{ .Values.config.worker_count }}"
  MAX_TASKS_PER_WORKER: "{{ .Values.config.max_tasks_per_worker }}"
  MAX_MEMORY_PER_WORKER: "{{ .Values.config.max_mem_per_worker }}"
  DATAFOLD_RATELIMIT_ENABLED: "{{ .Values.config.ratelimit_enabled }}"
  DATAFOLD_LOGGING_ENABLED: "{{ .Values.config.logging_enabled }}"
  DATAFOLD_SINGLE_TENANT_DEPLOY: "{{ .Values.config.single_tenant_deploy }}"
  DATAFOLD_MAIL_PORT: "{{ .Values.config.mail_port }}"
  DATAFOLD_MAIL_USE_TLS: "{{ .Values.config.mail_use_tls }}"
  DATAFOLD_MAIL_USE_SSL: "{{ .Values.config.mail_use_ssl }}"
  DATAFOLD_ENABLE_SSRF_PROTECTION: "{{ .Values.config.enable_ssrf_protection }}"
  DATAFOLD_APP_VERSION: "{{ .Values.config.max_mem_per_worker }}"
