apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datafold.configmap" . }}
data:
  PYTHONUNBUFFERED: "0"
  DATAFOLD_WEB_WORKERS: "{{ .Values.config.webWorkers }}"
  GITHUB_SERVER: "{{ .Values.config.githubServer }}"
  DEV_NAME: "{{ .Release.Name }}"
  INSTALLATION_NAME: "{{ .Release.Name }}"
  WORKERS_COUNT: "{{ .Values.config.workerCount }}"
  MAX_TASKS_PER_WORKER: "{{ .Values.config.maxTasksPerWorker }}"
  MAX_MEMORY_PER_WORKER: "{{ .Values.config.maxMemPerWorker }}"
  DATAFOLD_RATELIMIT_ENABLED: "{{ .Values.config.ratelimitEnabled }}"
  DATAFOLD_LOGGING_ENABLED: "{{ .Values.config.loggingEnabled }}"
  DATAFOLD_SINGLE_TENANT_DEPLOY: "{{ .Values.config.singleTenantDeploy }}"
  DATAFOLD_MAIL_PORT: "{{ .Values.config.mailPort }}"
  DATAFOLD_MAIL_USE_TLS: "{{ .Values.config.mailUseTls }}"
  DATAFOLD_MAIL_USE_SSL: "{{ .Values.config.mailUseSsl }}"
  DATAFOLD_ENABLE_SSRF_PROTECTION: "{{ .Values.config.enableSsrfProtection }}"
  DATAFOLD_APP_VERSION: "{{ .Values.config.maxMemPerWorker }}"
