apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datafold.configmap" . }}
data:
  PYTHONUNBUFFERED: "0"
  DATAFOLD_ALERTS_WITH_MULTIDIM_AND_MULTIFIELD: "{{ .Values.config.alertsWithMultiDimAndMultiField }}"
  DATAFOLD_APP_VERSION: "{{ .Values.config.maxMemPerWorker }}"
  DATAFOLD_CONTENT_SECURITY_POLICY: "{{ .Values.config.contentSecurityPolicy}}"
  DATAFOLD_DATADOG_AGENT_ADDRESS: '{{ include "datafold.datadog.logs.host" . }}:{{ include "datafold.datadog.logs.port" . }}'
  DATAFOLD_DATADOG_METRICS_ADDRESS: '{{ include "datafold.datadog.metrics.host" . }}:{{ include "datafold.datadog.metrics.port" . }}'
  DATAFOLD_DATE_FORMAT: "{{ .Values.config.dateFormat }}"
  DATAFOLD_ENABLE_GRAPH_INVARIANTS_CHECKS: "{{ .Values.config.enableGraphInvariantsChecks }}"
  DATAFOLD_ENABLE_SSRF_PROTECTION: "{{ .Values.config.enableSsrfProtection }}"
  DATAFOLD_ENFORCE_HTTPS: "{{ .Values.config.enforceHttps }}"
  DATAFOLD_FLOAT_FORMAT: "{{ .Values.config.floatFormat }}"
  DATAFOLD_GOOGLE_OAUTH_REQUEST_BQ: "{{ .Values.config.googleOauthRequestBQ }}"
  DATAFOLD_HOST: "https://{{ .Values.global.serverName }}"
  DATAFOLD_LINEAGE_TESTING_DB: "{{ .Values.config.lineageTestingDb }}"
  DATAFOLD_LOG_LEVEL: "{{ .Values.config.logLevel }}"
  DATAFOLD_LOGGING_ENABLED: "{{ .Values.config.loggingEnabled }}"
  DATAFOLD_MAIL_PORT: "{{ .Values.config.mailPort }}"
  DATAFOLD_MAIL_USE_TLS: "{{ .Values.config.mailUseTls }}"
  DATAFOLD_MAIL_USE_SSL: "{{ .Values.config.mailUseSsl }}"
  DATAFOLD_RATELIMIT_ENABLED: "{{ .Values.config.ratelimitEnabled }}"
  DATAFOLD_SINGLE_TENANT_DEPLOY: "{{ .Values.config.singleTenantDeploy }}"
  DATAFOLD_TIME_FORMAT: "{{ .Values.config.timeFormat }}"
  DATAFOLD_WEB_WORKERS: "{{ .Values.config.webWorkers }}"
  DD_DOGSTATSD_DISABLE: "{{ .Values.config.ddDogStatsDisable }}"
  DD_ENV: "{{ .Values.global.datadog.env }}"
  DD_TRACE_ENABLED: "{{ .Values.config.ddTraceEnabled }}"
  DEV_NAME: '{{ .Values.global.deployment }}'
{{- if .Values.config.githubServer }}
  GITHUB_SERVER: "{{ .Values.config.githubServer }}"
{{- end }}
{{- if .Values.config.gitlabServer }}
  GITLAB_SERVER: "{{ .Values.config.gitlabServer }}"
{{- end }}
  INSTALLATION_NAME: '{{ .Values.global.deployment }}'
  DATAFOLD_CELERY_RESULT_EXPIRES: "86400"
  DATAFOLD_CUSTOMER_ADAPTATION: "{{ .Values.config.customerAdaptation }}"
  DATAFOLD_DATADOG_APM_ADDRESS: '{{ include "datafold.datadog.apm.host" . }}:{{ include "datafold.datadog.apm.port" . }}'
  DD_REMOTE_CONFIGURATION_ENABLED: "false"
