apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "datafold.configmap" . }}
data:
  PYTHONUNBUFFERED: "0"
  DATAFOLD_ALERTS_WITH_MULTIDIM_AND_MULTIFIELD: "{{ .Values.config.alertsWithMultiDimAndMultiField }}"
  DATAFOLD_ENABLE_PROCESS_PROTECTION: "{{ .Values.config.enableProcessProtection }}"
  DATAFOLD_APP_VERSION: "{{ .Values.config.maxMemPerWorker }}"
  DATAFOLD_CONTENT_SECURITY_POLICY: "{{ .Values.config.contentSecurityPolicy}}"
  DATAFOLD_DATE_FORMAT: "{{ .Values.config.dateFormat }}"
  DATAFOLD_ENABLE_GRAPH_INVARIANTS_CHECKS: "{{ .Values.config.enableGraphInvariantsChecks }}"
  DATAFOLD_ENABLE_SSRF_PROTECTION: "{{ .Values.config.enableSsrfProtection }}"
  DATAFOLD_ENFORCE_HTTPS: "{{ .Values.config.enforceHttps }}"
  DATAFOLD_FLOAT_FORMAT: "{{ .Values.config.floatFormat }}"
  DATAFOLD_GOOGLE_OAUTH_REQUEST_BQ: "{{ .Values.config.googleOauthRequestBQ }}"
  DATAFOLD_HOST: "https://{{ .Values.global.serverName }}"
  DATAFOLD_LINEAGE_TESTING_DB: "{{ .Values.config.lineageTestingDb }}"
  DATAFOLD_LOG_LEVEL: "{{ .Values.config.logLevel }}"
  DATAFOLD_LOGGING_ENABLED: "{{ .Values.config.loggingEnabled }}"
  DATAFOLD_MONITORING_PROVIDER: "{{ .Values.config.monitoringProvider }}"
  DATAFOLD_METRICS_ENABLED: "{{ .Values.config.metricsEnabled }}"
  DATAFOLD_SIGNOZ_ENDPOINT: "{{ .Values.global.signoz.endpoint }}"
{{- if .Values.global.signoz.ingestionKey }}
  DATAFOLD_SIGNOZ_INGESTION_KEY: "{{ .Values.global.signoz.ingestionKey }}"
{{- end }}
  DATAFOLD_MAIL_PORT: "{{ .Values.config.mailPort }}"
  DATAFOLD_MAIL_USE_TLS: "{{ .Values.config.mailUseTls }}"
  DATAFOLD_MAIL_USE_SSL: "{{ .Values.config.mailUseSsl }}"
  DATAFOLD_RATELIMIT_ENABLED: "{{ .Values.config.ratelimitEnabled }}"
  DATAFOLD_RATELIMIT_HIGHLOAD_PER_MINUTE: "{{ .Values.config.rateLimitHighLoadPerMinute }}"
  DATAFOLD_SINGLE_TENANT_DEPLOY: "{{ .Values.config.singleTenantDeploy }}"
  DATAFOLD_TIME_FORMAT: "{{ .Values.config.timeFormat }}"
  DATAFOLD_WEB_WORKERS: "{{ .Values.config.webWorkers }}"
  DD_DOGSTATSD_DISABLE: "{{ .Values.config.ddDogStatsDisable }}"
  DD_ENV: "{{ .Values.global.datadog.env }}"
  DD_TRACE_ENABLED: "{{ .Values.config.ddTraceEnabled }}"
  DEV_NAME: '{{ .Values.global.deployment }}'
{{- if .Values.config.githubServer }}
  GITHUB_SERVER: "{{ .Values.config.githubServer }}"
{{- end }}
{{- if .Values.config.portalCertData }}
  PORTAL_CERT_DATA: "{{ .Values.config.portalCertData }}"
{{- end }}
{{- if .Values.config.temporalAddress }}
  TEMPORAL_ADDRESS: "{{ .Values.config.temporalAddress }}"
{{- end }}
{{- if .Values.config.temporalNamespace }}
  TEMPORAL_NAMESPACE: "{{ .Values.config.temporalNamespace }}"
{{- end }}
{{- if .Values.config.gitlabServer }}
  GITLAB_SERVER: "{{ .Values.config.gitlabServer }}"
{{- end }}
{{- if (index .Values "storage-worker" "install") }}
  DATAFOLD_STORAGE_WORKER_DEPLOYED: "true"
{{- end }}
{{- if (eq .Values.config.permitUnsafeLocalStorageMode "true" ) }}
  DATAFOLD_PERMIT_UNSAFE_LOCALSTORAGE_MODE: "true"
{{- end }}
{{- if .Values.secrets.apiOrgCreationDonorTokens }}
  DATAFOLD_API_ORG_CREATION_DONOR_TOKENS: "{{ .Values.secrets.apiOrgCreationDonorTokens }}"
{{- end }}
  INSTALLATION_NAME: '{{ .Values.global.deployment }}'
  DATAFOLD_CELERY_RESULT_EXPIRES: "86400"
  DATAFOLD_CUSTOMER_ADAPTATION: "{{ .Values.config.customerAdaptation }}"
  DD_REMOTE_CONFIGURATION_ENABLED: "false"
{{- range $custom_var := .Values.config.customVars }}
  {{ $custom_var.name }}: {{ $custom_var.value | quote }}
{{- end }}
