apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: datafold-redis
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: datafold
