apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datafold.secrets" . }}
type: Opaque
data:
  DATAFOLD_DB_ENCRYPTION_KEY: {{ .Values.secrets.database.encryption_key | b64enc }}
  DATAFOLD_INSTALL_PASSWORD: {{ .Values.secrets.install_me_password | b64enc }}
  DATAFOLD_MAIL_SERVER: {{ .Values.secrets.mail.server | b64enc }}
  DATAFOLD_MAIL_USERNAME: {{ .Values.secrets.mail.username | b64enc }}
  DATAFOLD_MAIL_PASSWORD: {{ .Values.secrets.mail.password | b64enc }}
  DATAFOLD_MAIL_DEFAULT_SENDER: {{ .Values.secrets.mail.default_sender | b64enc }}
  DATAFOLD_CLICKHOUSE_PASSWORD: {{ .Values.secrets.clickhouse.password | b64enc }}
  DATAFOLD_CLICKHOUSE_USER: {{ .Values.secrets.clickhouse.user | b64enc }}
