apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datafold.secrets" . }}
type: Opaque
data:
  DATAFOLD_DB_ENCRYPTION_KEY: {{ .Values.secrets.database.encryptionKey | b64enc }}
  DATAFOLD_INSTALL_PASSWORD: {{ .Values.secrets.installMePassword | b64enc }}
  DATAFOLD_MAIL_SERVER: {{ .Values.secrets.mail.server | b64enc }}
  DATAFOLD_MAIL_USERNAME: {{ .Values.secrets.mail.username | b64enc }}
  DATAFOLD_MAIL_PASSWORD: {{ .Values.secrets.mail.password | b64enc }}
  DATAFOLD_MAIL_DEFAULT_SENDER: {{ .Values.secrets.mail.defaultSender | b64enc }}
  DATAFOLD_CLICKHOUSE_PASSWORD: {{ .Values.secrets.clickhouse.password | b64enc }}
  DATAFOLD_CLICKHOUSE_USER: {{ .Values.secrets.clickhouse.user | b64enc }}
  DATAFOLD_POSTGRES_USER: {{ .Values.secrets.postgres.user | b64enc }}
  DATAFOLD_POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | b64enc }}
  DATAFOLD_POSTGRES_DB: {{ .Values.secrets.postgres.database | b64enc }}
  DATAFOLD_REDIS_PASSWORD: {{ .Values.secrets.redis.password | b64enc }}
  DATAFOLD_DD_API_KEY: {{ .Values.secrets.datadog.apiKey | b64enc }}
