{{- if (eq .Values.global.manageSecretsYourself false) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datafold.secrets" . }}
type: Opaque
data:
  DATAFOLD_DB_ENCRYPTION_KEY: {{ .Values.secrets.database.encryptionKey | b64enc }}
  DATAFOLD_INSTALL_PASSWORD: {{ .Values.secrets.installMePassword | b64enc }}
  DATAFOLD_MAIL_SERVER: {{ .Values.secrets.mail.server | b64enc }}
  DATAFOLD_MAIL_USERNAME: {{ .Values.secrets.mail.username | b64enc }}
  DATAFOLD_MAIL_PASSWORD: {{ .Values.secrets.mail.password | b64enc }}
  DATAFOLD_MAIL_DEFAULT_SENDER: {{ .Values.secrets.mail.defaultSender | b64enc }}
  DATAFOLD_CLICKHOUSE_PASSWORD: {{ .Values.secrets.clickhouse.password | b64enc }}
  DATAFOLD_CLICKHOUSE_USER: {{ .Values.secrets.clickhouse.user | b64enc }}
  DATAFOLD_POSTGRES_USER: {{ .Values.secrets.postgres.user | b64enc }}
  DATAFOLD_POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | b64enc }}
  DATAFOLD_RO_DATABASE_USER: {{ .Values.secrets.postgres.ro_user | b64enc }}
  DATAFOLD_RO_DATABASE_PASSWORD: {{ .Values.secrets.postgres.ro_password | b64enc }}
  DATAFOLD_DATADOG_PW: {{ .Values.secrets.postgres.datadog_password | b64enc }}
  DATAFOLD_POSTGRES_DB: {{ .Values.secrets.postgres.database | b64enc }}
  DATAFOLD_REDIS_PASSWORD: {{ .Values.secrets.redis.password | b64enc }}
  DATAFOLD_DATADOG_APPLICATION_ID: {{ .Values.secrets.datadog.applicationId | b64enc }}
  DATAFOLD_DATADOG_CLIENT_TOKEN: {{ .Values.secrets.datadog.clientToken | b64enc }}
  DATAFOLD_DD_API_KEY: {{ .Values.secrets.datadog.apiKey | b64enc }}
  DATAFOLD_DD_APP_KEY: {{ .Values.secrets.datadog.appKey | b64enc }}
  DATAFOLD_FRESHPAINT_FRONTEND_TOKEN: {{ .Values.secrets.freshpaint.frontendToken | b64enc }}
  DATAFOLD_FRESHPAINT_BACKEND_TOKEN: {{ .Values.secrets.freshpaint.backendToken | b64enc }}
  DATAFOLD_FRESHPAINT_URL: {{ .Values.secrets.freshpaint.url | b64enc }}
  DATAFOLD_AVO_INSPECTOR_FRONTEND_API_KEY: {{ .Values.secrets.freshpaint.avoToken | b64enc }}
  DATAFOLD_GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | b64enc }}
  DATAFOLD_GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleclientSecret | b64enc }}
  DATAFOLD_INTERCOM_APP_ID: {{ .Values.secrets.intercomId | b64enc }}
  DATAFOLD_PYLON_APP_ID: {{ .Values.secrets.pylonId | b64enc }}
  {{- if .Values.secrets.apiOrgCreationDonorTokens }}
  DATAFOLD_API_ORG_CREATION_DONOR_TOKENS: {{ .Values.secrets.apiOrgCreationDonorTokens | b64enc }}
  {{- end }}
  PORTAL_API_KEY: {{ .Values.secrets.operator.apiKey | b64enc }}
  PORTAL_URL: {{ .Values.secrets.operator.portalUrl | b64enc }}
  {{- if .Values.secrets.claude.datafoldDocsAuthKey }}
  DATAFOLD_DMA_DOCS_AUTH_KEY: {{ .Values.secrets.claude.datafoldDocsAuthKey | b64enc }}
  {{- end }}
{{- range $secret := .Values.global.customSecrets }}
  {{ $secret.name }}: {{ $secret.value | b64enc }}
{{- end }}
{{- end }}
