{{- if .Values.global.temporal.encryption.keys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datafold.temporal.encryptionSecret" . }}
  {{- with .Values.toplevel.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.toplevel.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- range $i, $k := .Values.global.temporal.encryption.keys }}
  TEMPORAL_ENCRYPTION_KEY_{{ $i }}: "{{ $k.id }}:{{ $k.value }}"
  {{- end }}
{{- end }}
