apiVersion: v2
name: datafold
description: Helm chart package to deploy Datafold on kubernetes.
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://www.datafold.com/logo.png

maintainers:
  - name: datafold
    email: support@datafold.com
    url: https://datafold.com

dependencies:
  - name: app
    version: "*.*.*"
    repository: file://charts/app
    condition: app.install
