replicaCount: 1

image:
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: datafold-docker-secret
nameOverride: ""
fullnameOverride: ""
terminationGracePeriodSeconds: "1800"

command: celery_worker

serviceAccount:
  create: true
  automount: true
  annotations: {}
  roleArn: ""
  name: "datafold-storage-worker"

worker:
  queues: "localstorage"
  tasks: 1
  memory: 850000
  count: 1
  tasks_ack_late: "false"

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true
  fsGroup: 1000
  fsGroupChangePolicy: "OnRootMismatch"

storage:
  dataSize: 100Gi
  storageClass: "sc-datafold-scratch"

securityContext:
  allowPrivilegeEscalation: false

resources:
  limits:
    memory: 15Gi
  requests:
    cpu: 1000m
    memory: 15Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

initContainers: []
