apiVersion: datafold.datafold.com/v1alpha1
kind: DatafoldApplication
metadata:
  name: datafold-deploy
  namespace: datafold
spec:
  global:
    serverName: datafold.example.com
    environment: production
    clusterName: datafold-cluster
    portalUrl: https://portal.datafold.com
    deployment: datafold-production
  # GCP Existing Load Balancer Configuration
  ingress:
    deployLoadBalancer: false  # Use existing load balancer
    internal: false
    google:
      # Network Endpoint Group name of the existing load balancer
      # Format: projects/{project-id}/zones/{zone}/networkEndpointGroups/{neg-name}
      networkEndpointGroupName: "projects/your-project-id/zones/us-central1-a/networkEndpointGroups/existing-neg-name"
