apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operator.fullname" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "operator.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        {{- include "operator.datadog.annotations" . | nindent 8 }}
      labels:
        {{- include "operator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: '{{ .Values.global.datafoldRepository }}/operator:{{ include "operator.version" . }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - poetry
            - run
            - kopf
            - run
            - --liveness=http://0.0.0.0:8080/healthz
            - --namespace={{ .Release.Namespace }}
            - /app/datafold_kopf/app_manager.py
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DD_VERSION
              value: '{{ include "operator.version" . }}'
            - name: ALLOW_ROLLBACK
              value: "{{ .Values.global.operator.allowRollback }}"
            - name: CLICKHOUSE_BACKUP_SCHEDULE
              value: "{{ .Values.global.operator.backupCronSchedule }}"
            - name: MAINTENANCE_WINDOW
              value: "{{ .Values.global.operator.maintenanceWindow }}"
            - name: DATADOG_METRICS_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DATADOG_METRICS_PORT
              value: '{{ include "datafold.datadog.metrics.port" . }}'
            - name: PORTAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "datafold.secrets" . }}
                  key: PORTAL_API_KEY
            - name: PORTAL_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "datafold.secrets" . }}
                  key: PORTAL_URL
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
