files: |
    (?x)^(
      jeeves/|
    )
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        types: [python]
        args:
          # Prevent Black from standardizing quotes
          - "-S"

          # Will not support 3.10 syntax forms otherwise
          - "--target-version"
          - "py311"

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.282'
    hooks:
      - id: ruff
        args: ['--fix']
        exclude: __init__.py
        types: [python]

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
