apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worker-temporal.fullname" . }}
  labels:
    {{- include "worker-temporal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "worker-temporal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "worker-temporal.datafold.annotations" . | nindent 8 }}
        {{- include "worker-temporal.datadog.annotations" . | nindent 8 }}
      labels:
        {{- include "worker-temporal.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.shellRepository }}/{{ .Values.global.datafoldImage }}:{{ .Values.global.datafoldVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- toYaml $.Values.command | nindent 10 }}
          envFrom:
            - configMapRef:
                name: {{ include "datafold.configmap" . }}
          env:
            {{ include "datafold.env" . | nindent 12 }}
            - name: DATAFOLD_DATADOG_CLIENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "datafold.secrets" . }}
                  key: DATAFOLD_DATADOG_CLIENT_TOKEN
            - name: DATAFOLD_DATADOG_APPLICATION_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "datafold.secrets" . }}
                  key: DATAFOLD_DATADOG_APPLICATION_ID
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
