apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scheduler.fullname" . }}
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "scheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "scheduler.datafold.annotations" . | nindent 8 }}
        {{- include "scheduler.datadog.annotations" . | nindent 8 }}
      labels:
        {{- include "scheduler.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.datafoldRepository }}/{{ .Values.global.datafoldImage }}:{{ .Values.global.datafoldVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["{{ .Values.command }}"]
          envFrom:
            - configMapRef:
                name: {{ include "datafold.configmap" . }}
          env:
            {{ include "datafold.env" . | nindent 12 }}
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - ps -ef | grep "celery beat" | grep -v grep
            initialDelaySeconds: 10
            periodSeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
