apiVersion: v1
kind: Service
metadata:
  name: {{ include "scheduler.fullname" . }}
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 5000
    targetPort: scheduler
    protocol: TCP
  selector:
    {{- include "scheduler.selectorLabels" . | nindent 4 }}
