replicaCount: 1

image:
  repository: redis
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
terminationGracePeriodSeconds: "30"

storage:
  size: 2Gi
  name: datafold-redis-storage
  storageClass: ""
  volumeId: ""

podAnnotations: {}

service:
  type: ClusterIP

resources:
  limits:
    memory: 6000Mi
  requests:
    cpu: 100m
    memory: 6000Mi

nodeSelector: {}

tolerations: []

affinity: {}
