replicaCount: 1

image:
  repository: redis
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
terminationGracePeriodSeconds: "30"

# Redis AOF (Append-Only File) rewrite settings for compaction
aof:
  autoRewritePercentage: 100  # Rewrite AOF when it grows 100% larger than last rewrite
  autoRewriteMinSize: "64mb"  # Minimum size for AOF rewrite

storage:
  dataSize: 50Gi
  name: datafold-redis-storage
  storageClass: ""
  dataVolumeId: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: false

securityContext:
  allowPrivilegeEscalation: false

service:
  type: ClusterIP

resources:
  limits:
    memory: 3Gi
  requests:
    cpu: 100m
    memory: 3Gi

nodeSelector: {}

tolerations:
  - key: clickhouse
    operator: "Equal"
    value: reserved

affinity:
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - clickhouse
          topologyKey: kubernetes.io/hostname
