replicaCount: 1

image:
  repository: redis
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
terminationGracePeriodSeconds: "30"

storage:
  dataSize: 2Gi
  name: datafold-redis-storage
  storageClass: ""
  dataVolumeId: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: false

securityContext:
  allowPrivilegeEscalation: false

service:
  type: ClusterIP

resources:
  limits:
    memory: 6000Mi
  requests:
    cpu: 100m
    memory: 6000Mi

nodeSelector: {}

tolerations: []

affinity:
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - clickhouse
          topologyKey: kubernetes.io/hostname
