replicaCount: 1
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.24"

imagePullSecrets:
nameOverride: ""
fullnameOverride: ""
terminationGracePeriodSeconds: "30"

service:
  typeOverride: ""
  nodePort: 31337
  loadBalancerIps: []

ingress:
  sslCertificate: ""
  deploy: false

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: false

securityContext:
  allowPrivilegeEscalation: false

resources:
  limits:
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
