replicaCount: 1
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.24"

imagePullSecrets:
nameOverride: ""
fullnameOverride: ""
terminationGracePeriodSeconds: "15"

service:
  typeOverride: ""
  nodePort: 31337
  loadBalancerIps: []

ingress:
  ingressClassOverride: ""
  deploy: false

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
