apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dfappmanagers.crds.datafold.com
spec:
  scope: Namespaced
  group: crds.datafold.com
  names:
    kind: DfAppManager
    plural: dfappmanagers
    singular: dfappmanager
    shortNames:
      - dfam
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                datafoldVersion:
                  type: string
                lastBackupRun:
                  type: string
                datafoldVersionOverride:
                  type: string
