apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres.data.pvc.name" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  annotations: {}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
{{- if .Values.storage.volumeId }}
  volumeName: {{ include "postgres.data.pv.name" . }}
  storageClassName: ""
{{- else }}
  {{ include "datafold.storageClass" . | nindent 2 }}
{{- end }}