apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres.data.pvc.name" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  annotations: {}
spec:
  accessModes:
    - ReadWriteOnce
  {{ include "datafold.storageClass" . | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
