apiVersion: v1
kind: Service
metadata:
  name: {{ include "datafold.postgres.server" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "datafold.postgres.port" . }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
