apiVersion: v2
name: datafold-crds
description: Helm chart package to deploy Datafold CRDs on kubernetes.
type: application
version: 0.1.1
appVersion: "1.0.0"
icon: https://www.datafold.com/logo.png

maintainers:
  - name: datafold
    email: support@datafold.com
    url: https://datafold.com
