replicaCount: 1

image:
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: datafold-docker-secret
nameOverride: ""
fullnameOverride: ""
terminationGracePeriodSeconds: "1800"

command: celery_worker

worker:
  queues: "celery,api,ci,interactive,freshpaint,alerts"
  tasks: 200
  memory: 850000
  count: 15

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true
  fsGroup: 1000
  fsGroupChangePolicy: "OnRootMismatch"

storage:
  dataSize: 100Gi
  storageClass: "sc-datafold-scratch"
  enabled: false

securityContext:
  allowPrivilegeEscalation: false

resources:
  limits:
    memory: 12000Mi
  requests:
    cpu: 1000m
    memory: 12000Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
