replicaCount: 1

image:
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: datafold-docker-secret
nameOverride: ""
fullnameOverride: ""
terminationGracePeriodSeconds: "600"

command: celery_worker

worker:
  queues: "celery,api,ci,interactive,freshpaint,alerts"
  tasks: 200
  memory: 850000
  count: 15

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    memory: 10000Mi
  requests:
    cpu: 1000m
    memory: 10000Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
