replicaCount: 1

image:
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: datafold-docker-secret
nameOverride: ""
fullnameOverride: ""
terminationGracePeriodSeconds: "300"

command: celery_worker

worker:
  queues: "interactive"
  tasks: 200
  memory: 850000
  count: 5

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsUser: 1000
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false

resources:
  limits:
    memory: 6000Mi
  requests:
    cpu: 100m
    memory: 6000Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
