replicaCount: 1

image:
  repository: us-docker.pkg.dev/datadiff-mm/datafold/dmadev
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: datafold-docker-secret

nameOverride: ""
fullnameOverride: ""
terminationGracePeriodSeconds: "30"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  roleArn: ""
  name: "datafold-dma"

jobServiceAccount:
  create: true
  automount: true
  annotations: {}
  name: "datafold-jobs"

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsUser: 0
  runAsNonRoot: false

securityContext:
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 9999 # Bogus port for headless service

resources:
  limits:
    cpu: 1000m
    memory: 60Gi
  requests:
    cpu: 1000m
    memory: 60Gi

storage:
  storageClass: "sc-datafold-aws"
  accessMode: ReadWriteOnce
  size: 200Gi
  mountPath: /data

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

dma:
  env: []
  ssh:
    port: 2222
    # Username for SSH access
    username: "datafold"

restartPolicy: Always